# Generated by Django 5.0.3 on 2024-04-03 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_remove_shop_product_alter_product_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
